import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_Components/Navbar/Navbar";
import TopBar from "./_Components/TopBar/TopBar";
import Footer from "./_Components/Footer/Footer";
import ShopByCategory from "./_Components/ShopByCategory/ShopByCategory";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";
import MySessionProvidr from "./_providers/MySessionProvidr";
import { CartContextProvider } from "./_context/CartContextProvider";
import { getUserCart } from "./_Components/ProductCart/card.actions";
import { Features } from "./_Components/Features/Features";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userCart = await getUserCart();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <SessionProvider> */}
        <MySessionProvidr>
          <CartContextProvider userCart={userCart}>
            <TopBar />
            <Navbar />
            <Toaster position="top-center" richColors />
            {children}
            <Features />
            <Footer />
          </CartContextProvider>
        </MySessionProvidr>
        {/* </SessionProvider>  */}
      </body>
    </html>
  );
}

// middelware
